In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [6]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [11]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [12]:
arr = np.array([[1,2],[3,4]])
print(arr.shape)

(2, 2)


In [13]:
print(arr.ndim)

2


In [14]:
arr.size

4

In [15]:
arr.dtype

dtype('int64')

In [16]:
arr = np.array([10,20,30,40,50])
print(arr[1])

20


In [21]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d[1,2])

6


In [22]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


In [33]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[:2, 1:3])

[[2 3]
 [5 6]]


In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(arr1 * arr2)


[5 7 9]
[ 4 10 18]


In [35]:
arr = np.array([1, 2, 3])
print(arr * 2)

[2 4 6]


In [36]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print(np.dot(mat1, mat2))

[[19 22]
 [43 50]]


In [37]:
arr = np.array([0, np.pi/2, np.pi])
print(np.sin(arr))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [39]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))
print(np.std(arr))
print(np.max(arr))
print(np.min(arr))

3.0
1.4142135623730951
5
1


In [40]:
ran_arr = np.random.rand(3,3)
print(ran_arr)

[[0.14121283 0.08975065 0.60139123]
 [0.63709251 0.80817798 0.43998896]
 [0.38524423 0.55958545 0.28346336]]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape(2,3)
print(arr_reshaped)

[[1 2 3]
 [4 5 6]]


In [42]:
arr_2d = np.array([[1, 2], [3, 4]])
print(arr_2d.flatten())

[1 2 3 4]


In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scaler = 10
print(arr + scaler)

[[11 12 13]
 [14 15 16]]


In [44]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [45]:
eigvals, eigvecs = np.linalg.eig(A)
print(eigvals)


[-0.37228132  5.37228132]


In [46]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print(x)

[2. 3.]


In [47]:
import pandas as pd
df = pd.DataFrame(np.array([[1, 2], [3, 4]]), columns=["A", "B"])
print(df)


   A  B
0  1  2
1  3  4
