In [1]:
!pip install scikit-learn

In [2]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original Data : ", data)

scaler = StandardScaler()
standardized_data = scaler.fit_transform(data)

print("standardized data :",standardized_data)

Original Data :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
standardized data : [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [27]:
from sklearn.model_selection import train_test_split
import numpy as np

X = np.arange(10).reshape((5,2))
y = np.array([0,1,0,1,0])


In [30]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)
print("Training Features :",X_train)
print("Testing Features :",X_test)

Training Features : [[8 9]
 [4 5]
 [0 1]
 [6 7]]
Testing Features : [[2 3]]


In [32]:
from sklearn.linear_model import LinearRegression
import numpy as np
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([1.1, 1.9, 3.0, 3.9, 5.1])

model = LinearRegression()
model.fit(X,y)

predication = model.predict(X)
print("Prediction :",predication)

Prediction : [1. 2. 3. 4. 5.]


In [33]:
from sklearn.metrics import mean_squared_error,r2_score
mse = mean_squared_error(y,predication)
r2 = r2_score(y,predication)

print("Mean Squared Error :",mse)
print("R-squared :",r2)

Mean Squared Error : 0.007999999999999988
R-squared : 0.9960159362549801


In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
iris = load_iris()

X,y = iris.data,iris.target
model = LogisticRegression(max_iter = 300)
model.fit(X,y)

prediction = model.predict(X)
print("Prediction :" , prediction)

Prediction : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [39]:
from sklearn.cluster import KMeans
import numpy as np
data = np.array([[1, 2], [1, 4], [1, 0],
                 [10, 2], [10, 4], [10, 0]])

kmeans = KMeans(n_clusters= 2,random_state = 0)
kmeans.fit(data)

print("CLuster centers : ",kmeans.cluster_centers_)
print("Labels :" , kmeans.labels_)

CLuster centers :  [[10.  2.]
 [ 1.  2.]]
Labels : [1 1 1 0 0 0]


In [41]:
from sklearn.feature_selection import SelectKBest,f_classif
from sklearn.datasets import load_iris
iris = load_iris()
X,y = iris.data,iris.target

selector = SelectKBest(score_func=f_classif,k=2)
X_new = selector.fit_transform(X,y)

print("Top 2 features :",X_new)

Top 2 features : [[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.

In [46]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

pipeline = Pipeline([
    ('scaler',StandardScaler()),
    ('svc', SVC(kernel='linear'))
])

pipeline.fit(X,y)
prediciton = pipeline.predict(X)
print("Prediction :",prediction)

Prediction : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [47]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import Ridge

diabetes = load_diabetes()
X,y = diabetes.data,diabetes.target

model = Ridge(alpha=1.0)
model.fit(X,y)
print("Coefficients :",model.coef_)

Coefficients : [  29.46611189  -83.15427636  306.35268015  201.62773437    5.90961437
  -29.51549508 -152.04028006  117.3117316   262.94429001  111.87895644]
